;-----------------------------------------------
; @AUTHOR : Muhammad Quwais Safutra
; @Copyright 2018BES
;-----------------------------------------------

CODERES SEGMENT PUBLIC
CODERES ENDS

DATARES SEGMENT PUBLIC
DATARES ENDS

ENVIRONMENT SEGMENT PUBLIC
ENVIRONMENT ENDS

INIT    SEGMENT PUBLIC
INIT    ENDS

TAIL    SEGMENT PUBLIC
TAIL    ENDS

TRANCODE        SEGMENT PUBLIC
TRANCODE        ENDS

TRANDATA        SEGMENT PUBLIC
TRANDATA        ENDS

TRANSPACE       SEGMENT PUBLIC
TRANSPACE       ENDS

TRANTAIL        SEGMENT PUBLIC
TRANTAIL        ENDS

ZEXEC_CODE      SEGMENT PUBLIC
ZEXEC_CODE      ENDS
